### PR TITLE
Add stack.yaml

### PR DESCRIPTION
**Pull request by snoyberg**
Can you confirm that, when building with this set of libraries, you get the same behavior reported before?

### CODE REVIEW

**Comment by erikd** [comment]
Thanks. I'll merge that when I get to the office tomorrow. I don't have my work account credentials on this machine.

**Comment by erikd** [comment]
Sorry, to reply the the question above, I saw this problem with a range of wai/warp/http-conduit versions.

It originally manifested with wai==3.0.3.0, warp=3.0.13.1 and http-conduit==2.1.5.1.

My most recent testing however has been with wai==3.2.1.1, warp==3.2.8 and http-conduit==2.2.0.1. I have not been using http-client.

As far as I can tell they all behave basically the same with regard to this problem.

**Comment by erikd** [comment]
@snoyberg I've just built this project using stack (and your stack.yaml file) on my personal laptop and triggered the issue on the third run.

**Comment by snoyberg** [comment]
Cool, that'll make debugging easier hopefully. I'm planning on looking at
this later today or tomorrow.

**Pull request merged**
